language: bash

sudo: required
services:
- docker
cache:
  directories:
    - $HOME/.m2

script:
  - "./ci/bootstrap-build.sh /app/src/ci/build.sh && ./ci/deploy.sh"

before_cache:
 - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

notifications:
  slack: akvo:ZLetmotGiT22QryK6pR5bnFS
