language: java

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache

before_install:
  - docker pull akvo/flow-build
  - ./docker/bootstrap-debug.sh

script:
  - docker inspect -f '{{json .Mounts}}' flow-build
