language: java

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - echo "before_install" #docker pull akvo/flow-maven-build

script:
  - docker build -t akvo/flow-maven-build .
  - "./ci/bootstrap-build.sh /app/src/ci/build.sh && ./ci/deploy.sh"
