package org.waterforpeople.mapping.app.gwt.client.util;

import com.google.gwt.i18n.client.Constants;


/**
 * holds all strings displayed in the UI
 * 
 * @author Christopher Fagiani
 * 
 */
public interface TextConstants extends Constants{
	public String addItemToDashboard();
	public String selectPortlets();
	public String done();
	public String portlets();
	public String description();
	public String surveyGroup();
	public String survey();
	public String questionGroup();
	public String loading();
	public String error();
	public String couldNotLoadSurveyGroups();
	public String errorTracePrefix();
	public String inputError();
	public String mustSelectSurveyGroup();
	public String questionText();
	public String attribute();
	public String pointType();
	public String saveComplete();
	public String selectSurveyForInclusion();
	public String generate();
	public String addSelected();
	public String removeSelected();
	public String fileContents();
	public String selectedSurveys();
	public String includeDB();
	public String notificationEmail();
	public String pleaseCorrect();
	public String requestSubmitted();
	public String emailWillBeSent();
	public String noDBSurveyMandatory();
	public String emailMandatory();
	public String editSubscriptions();
	public String save();
	public String close();
	public String dateAndEmailMandatory();
	public String remove();
	public String add();
	public String editHelpMedia();
	public String discardChanges();
	public String addHelpItem();
	public String selectionCriteria();
	public String end();
	public String start();
	public String assignmentDetails();
	public String tripName();
	public String selectedDevices();
	public String devices();
	public String nameMandatory();
	public String startMandatory();
	public String endMandatory();
	public String surveyMandatory();
	public String deviceMandatory();
	public String copySurvey();
	public String destinationGroup();
	public String newSurveyName();
	public String copy();
	public String cancel();
	public String noSurveyGroups();
	public String copying();
	public String loadingQuestionGroups();
	public String savingNewQuestionGroups();
	public String loadingQuestionsForGroup();
	public String loadingDetailsForGroup();
	public String question();
	public String savingDetailsForGroup();
	public String editTranslations();
	public String kinyarwanda();
	public String french();
	public String spanish();
	public String text();
	public String selectSurvey();
	public String ok();
	public String selectSurveyFirst();
	public String expires();
	public String authType();
	public String maxUses();
	public String token();
	public String maxUseNumeric();
	public String mustSelectSurvey();
	public String authUrl();
	public String name();
	public String findUser();
	public String userMandatoryForAuth();
	public String selectUser();
	public String userName();
	public String emailAddress();
	public String permissions();
	public String search();
	public String addUser();
	public String userUpdated();
	public String delete();
	public String deleteComplete();
	public String userDeleted();
	public String select();
	public String emailUsernameMandatory();
	public String apManagerTitle();
	public String apManagerDescription();
	public String id();
	public String communityCode();
	public String latitude();
	public String longitude();	
	public String collectionDate();
	public String editDelete();
	public String showErrors();
	public String deleteMatches();
	public String createAP();
	public String warning();
	public String thisWillDeleteAllAP();
	public String general();
	public String media();
	public String attributes();
	public String scoreDetails();
	public String status();
	public String scoreMakeup();
	public String scoreDate();
	public String score();
	public String photoUrl();
	public String upload();
	public String uploadComplete();
	public String waitForRotate();
	public String photoCaption();
	public String countryCode();
	
}
