APPNAME = 'akvo-flow'

require 'colored'
require 'rake-pipeline'
require 'i18n-docs'
require 'fileutils'

def pipeline
  Rake::Pipeline::Project.new('Assetfile')
end

def pipeline_public
  Rake::Pipeline::Project.new('AssetfilePublic')
end

desc "Clean #{APPNAME}"
task :clean do
  pipeline.clean
  system "rm -rf assets/js/vendor"
end

desc "Build #{APPNAME}"
task :build => :clean do
  pipeline.invoke
  pipeline_public.invoke
end

desc "Watch for changes"
task :watch do
  system "bundle exec guard start"
end

desc "Watch for changes in the background"
task :watchbg do
  system "bundle exec guard start --no-interactions"
end
