//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.05 at 05:55:36 PM MDT 
//

package com.gallatinsystems.survey.domain.xml;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.gallatinsystems.survey.domain.xml package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes
     * for package: com.gallatinsystems.survey.domain.xml
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Survey }
     */
    public Survey createSurvey() {
        return new Survey();
    }

    /**
     * Create an instance of {@link Heading }
     */
    public Heading createHeading() {
        return new Heading();
    }

    /**
     * Create an instance of {@link AltText }
     */
    public AltText createAltText() {
        return new AltText();
    }

    /**
     * Create an instance of {@link Help }
     */
    public Help createHelp() {
        return new Help();
    }

    /**
     * Create an instance of {@link ValidationRule }
     */
    public ValidationRule createValidationRule() {
        return new ValidationRule();
    }

    /**
     * Create an instance of {@link Question }
     */
    public Question createQuestion() {
        return new Question();
    }

    /**
     * Create an instance of {@link Options }
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link Levels }
     */
    public Levels createLevels() {
        return new Levels();
    }

    /**
     * Create an instance of {@link Level }
     */
    public Level createLevel() {
        return new Level();
    }

    /**
     * Create an instance of {@link Dependency }
     */
    public Dependency createDependency() {
        return new Dependency();
    }

    /**
     * Create an instance of {@link Option }
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link Text }
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link QuestionGroup }
     */
    public QuestionGroup createQuestionGroup() {
        return new QuestionGroup();
    }

}
