//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.05 at 05:55:36 PM MDT 
//

package com.gallatinsystems.survey.domain.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}heading"/>
 *         &lt;element ref="{}question" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "heading",
        "question"
})
@XmlRootElement(name = "questionGroup")
public class QuestionGroup {

    @XmlElement(required = true)
    protected Heading heading;
    @XmlElement(required = true)
    protected List<Question> question;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String order;
    @XmlAttribute(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String repeatable;
    /**
     * Gets the value of the heading property.
     * 
     * @return possible object is {@link Heading }
     */
    public Heading getHeading() {
        return heading;
    }

    public void setQuestion(List<Question> question) {
        this.question = question;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value allowed object is {@link Heading }
     */
    public void setHeading(Heading value) {
        this.heading = value;
    }

    /**
     * Gets the value of the question property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the question property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getQuestion().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Question }
     */
    public List<Question> getQuestion() {
        if (question == null) {
            question = new ArrayList<Question>();
        }
        return this.question;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return possible object is {@link String }
     */
    public String getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setOrder(String value) {
        this.order = value;
    }
    
    public void setRepeatable(String repeatable) {
        this.repeatable = repeatable;
    }
    
    public String getRepeatable() {
        return repeatable;
    }

}
